etianen/django-reversion

src/reversion/admin.py
Use inline.get_queryset instead of inline.queryset to correctly revert modeladmins with tabular/stacked inlines.
=> Update admin.py to use inline.get_queryset

src/reversion/migrations/0002_auto_20141216_1509.py, src/reversion/models.py
As outlined in http://dev.mysql.com/doc/refman/5.5/en/charset-unicode-upgrading.html
> InnoDB has a maximum index length of 767 bytes, so for utf8 or utf8mb4 columns, you can index a maximum of 255 or 191 characters, respectively. If you currently have utf8 columns with indexes longer than 191 characters, you will need to index a smaller number of characters. In an InnoDB table, these column and index definitions are legal:
This change ensures those using the InnoDB storage engine in MySQL with utf8mb4_* collations can use reversion.
=> Support for MySQL utf8mb4

src/reversion/admin.py
=> Fix Django 1.8+ warnings by importing from django.contrib.admin.utils (plural)

src/reversion/models.py
Importing of django.contrib.contenttypes.generic is deprecated since Django 1.7. https://docs.djangoproject.com/en/1.7/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericForeignKey
Deprecated since version 1.7:
This class used to be defined in django.contrib.contenttypes.generic. Support for importing from this old location will be removed in Django 1.9.
=> Fix deprecated import of GenericForeignKey

src/reversion/admin.py
RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
=> Update admin.py to avoid RemovedInDjango19Warning

src/reversion/management/commands/deleterevisions.py
`./manage.py deleterevisions` should now work on both Python2 and 3 this change resolves the error below when running on Python3
```
choice = raw_input("Are you sure you want to delete theses revisions? [y|N] ")
NameError: name 'raw_input' is not defined
```
=> Fix for deleterevisions on Py3

src/reversion/revisions.py
When copying instances in Django, the standard way of doing it is setting an object's PK as None. As of some versions of Django, when a related field is assigned, a save event is triggered and if that assignment was done on the object that was being copied and had a PK of None it created a conflict with django-reversion.
When reversion tried to save changes done to the object, it could not locate the PK of the object, raising an Exception since the int() conversion of None returns a ValueError.
This PR fixes it by checking that the object that will be saved in the revision has a PK that is not None and thus skips it.
=> Properly handles a scenario when an instance's PK is None

src/tests/test_reversion/tests.py
This verifies that #391 has indeed been fixed.
Adds a test that verifies that creating and deleting a model instance
within a reversion does not create a new version.
=> Test that creating and deleting instance does not create version

src/reversion/management/commands/deleterevisions.py
When prompting the user for a y/n choice, the deleterevisions command
was failing for me in Python 2.7.9 because it was falling back to use
input() instead of raw_input().
This fallback is appropriate for Python 3 in which raw_input() was
replaced by input(), but should never be done in Python 2 because there
the input() function evaluates the user input as code.
I am not really sure why the attempted Python 2/3 recognition technique
of assigning the raw_input function to itself fails to work correctly
for me, but this restructured version should accomplish the same thing
with less chance of incorrectly assuming it is in Python 3.
=> Fix deleterevisions' user choice prompt to work with Python 2

docs/diffs.rst
`reversion.get_for_object()` should return versions in a reversed-chronological order. So, `available_versions[0]` would reflect the latest change.
=> Change order of `available_versions` in example

docs/index.rst
This replaces "manage.py syncdb" which is deprecated and will be removed in Django 1.9
=> Updated index to use "manage.py migrate"

docs/diffs.rst
Linking to existing project to do comparison with admin integration.
=> Linking to existing project to do comparison

MANIFEST.in
This would allow to run the tests when building packages for a distribution e.g.
Debian.
=> Include tests in pypi source tarball.

src/reversion/management/commands/createinitialrevisions.py
a tiny performance optimization.
=> Disable default ordering defined on Model.Meta

src/reversion/admin.py
Both `recover_view` (at https://github.com/etianen/django-reversion/blob/master/src/reversion/admin.py#L209) and `revision_view` (at https://github.com/etianen/django-reversion/blob/master/src/reversion/admin.py#L219) call `get_object_or_404` which will raise a ValueError if a non-integer is passed to the version_id parameter.
=> Return 404 rather then 500 due to ValueError in reversion view methods.

reversion/migrations/0003_auto_20160601_1600.py
As mentioned in #541, de_dupe_version_table in migration 0003 is very heavy. At least in my case, it turned out that the query wasn't necessary at all:
```
>>> from reversion.models import Version
>>> from django.db import models
>>> keep_version_ids = Version.objects.order_by().values_list(
"revision_id",
"content_type_id",
"object_id",
).annotate(
max_pk=models.Max("pk"),
).values_list("max_pk", flat=True)
>>> keep_version_ids.count()
806866
>>> Version.objects.all().count()
806866
```
The subsequent statement is what takes so incredibly long, so this pull request would be a significant speedup in this case (I don't know how likely this is, but at least it was true for me)
=> do not do heavy queries if no objects would be deleted anyway

reversion/admin.py, tests/test_app/tests/test_admin.py
As per conversation in #564 (where I misnamed the potential variables, but we ultimately settled on a pair), this adds new context variables to a VersionAdmin when rendering the changeform view, which allow the template or middleware to establish which view is being rendered. Their absence indicates it was not the view in question.
=> added `revert` and `recover` context variables to mirror Django's

docs/_include/signal-args.rst, docs/index.rst, docs/signals.rst, reversion/revisions.py, reversion/signals.py, tests/test_app/tests/test_api.py, tox.ini
Rationale: https://github.com/etianen/django-reversion/issues/571
Related commit: 09ce3764c1404747ebb90379cd79e193f3f58164
=> Reintroduce pre_revision_commit and post_revision_commit signals

docs/api.rst
This fixes a copy&paste mistake in API docs.
=> Fix docs for `Version.objects.get_for_object_reference`

reversion/admin.py
Fixed #547: Misleading datetime in revert message
=> Fixed #547: Misleading datetime in revert message

reversion/models.py
All supported django versions have `'postgresql'`, not `'postgres'` vendor name for PostgreSQL database:
- [django 1.8](https://github.com/django/django/blob/stable/1.8.x/django/db/backends/postgresql_psycopg2/base.py#L68)
- [django 1.9](https://github.com/django/django/blob/stable/1.9.x/django/db/backends/postgresql/base.py#L68)
- [django 1.10](https://github.com/django/django/blob/stable/1.10.x/django/db/backends/postgresql/base.py#L68)
But in django_reversion [_safe_subquery](https://github.com/etianen/django-reversion/blob/master/reversion/models.py#L297) function `'postgres'` is used in comparison. As a result, code like
Version.objects.get_deleted(MyModel)
will do some in-memory stuff, which results in significantly lower performance.
=> Fix postgresql vendor name

CHANGELOG.rst
Noticed the ordering of the `Revision` and `Version` models was reversed in 2.0, [in this commit](https://github.com/etianen/django-reversion/commit/8a3a6c369fd4d16253884dd31c98969065d1e26e#diff-848d9ceb3ff77cf47a950aa6c22852daR99). This caused a little confusion when updating, since `.last()` was now `.first()`.
A changelog entry on this might help future upgraders to check their code.
Thanks for your work on the library.
=> Add changelog note on models ordering change done in 2.0.0

CHANGELOG.rst
Was updating from 1.10.1 to 2.0.8 and found this additional breaking change. 
Here's when it was changed: https://github.com/etianen/django-reversion/commit/85ae48c3266d726e38d45778dca6be26f0465647#diff-848d9ceb3ff77cf47a950aa6c22852daL190
=> Update changelog with additional breaking change in API

reversion/views.py
Currently this code fails if `request.user == None` with `AttributeError: 'NoneType' object has no attribute 'is_authenticated'`.
It could be worth adding a test which I can do in the evening.
Fixes #648
=> Updated '_set_user_from_request' to make sure that request user is not empty

reversion/admin.py, tests/test_app/migrations/0001_initial.py, tests/test_app/models.py, tests/test_app/tests/test_admin.py
Issue is as described in #661. Fix is pretty straightforward, just needed to quote/unquote in the right places.
Also adds unit tests that demonstrate issue and verify the fix.
=> Fix issue with admin and special characters in primary keys

CHANGELOG.rst, docs/admin.rst
With the former:
```python-traceback
TypeError: register() got an unexpected keyword argument 'ignore_duplicate_revisions'
```
=> Fix `ignore_duplicate_revisions` to `ignore_duplicates` in CHANGELOG.rst

reversion/admin.py, reversion/models.py, reversion/templates/reversion/object_history.html, tests/test_app/tests/base.py
Addresses #725 
Accessing `reversion.comment` is now advised via `reversion.get_comment()` 
...should be documented and hinted in the release notes.
=> Leave change_message/comment as JSON

docs/commands.rst, reversion/management/commands/createinitialrevisions.py, tests/test_app/tests/test_commands.py
I needed to add a meta model with every initial revision.
Example:
```
./manage.py createinitialrevisions your_app.YourModel --meta="{\"your_app.RevisionMeta\": {\"hello\": \"world\"}}"
```
=> Add meta param for createinitialrevisions command

docs/middleware.rst, docs/views.rst, reversion/middleware.py, reversion/views.py, tests/test_app/tests/test_views.py, tests/test_app/views.py
Through the custom methods `RevisionMixin.revision_request_creates_revision` and `RevisionMiddleware.request_creates_revision`, as well as an additional optional parameter for the view decorator `create_revision`, the user can provide a predicate that may extend or override the default "reject if GET, HEAD or OPTIONS" criterion.
I'm aware that this behaviour can be achieved by not using the mixin / middleware / view decorator and manually annotating blocks of code. However, I believe this would simplify things by centralizing any additional, all-covering criteria.
=> Allow overriding of `_request_creates_revision`.

reversion/revisions.py, tests/test_app/tests/test_api.py
This adds meta, user, and comment support to the `_ContextWrapper`.
I found it nice to build/test my own `create_revision`.
```python
def create_revision_for_obj(user, manage_manually=False, using=None, atomic=True, **kwargs):
from reversion.models import Revision
using = using or router.db_for_write(Revision)
return _ContextWrapper(_create_revision_context, (manage_manually, using, atomic), ObjMeta, user, **kwargs)
```
I then could use it like so (as user and the meta obj were always required):
```python
meta_values = {'hello': 'world'}
with create_revision_for_obj(request.user, **meta_values):
obj.save()
```
Compared to this:
```python
meta_values = {'hello': 'world'}
with create_revision():
add_meta(ObjMeta, **meta_values)
set_user(request.user)
obj.save()
```
I'm not particularly …
=> Add fields to context wrapper

reversion/models.py
Even if you have a M2M relation to `django.contrib.auth.models.User` or you call `django.contrib.auth.get_user_model()` you can’t access `Version.field_dict` attributes.
In my case I had a Model like this:
```
@reversion.register()
class MyModel(models.Model):
users = models.ManyToMany(get_user_model(), related_name='my_models', blank=True)
(...)
```
When I was working on a low-level codebase around Version objects, I found that calling `version_obj.field_dict[field_name]` doesn't works if a M2M was present pointing to User. Any other M2M relation works smoothly. 
https://github.com/etianen/django-reversion/blob/3d05eed4c6e242bf7f0e8bd4726918bb3a771764/reversion/models.py#L269-L274
The problem is that `m2m_data` is not always available and it raises a `TypeError: argument of type …
=> Fixed TypeError exception when accessing m2m_data attributes

.travis.yml, reversion/models.py
The test suite itself runs in 4 instead of 7 seconds on my local machine.
The NOT IN that was previously used grows exponentially with the data size, whereas the NOT EXISTS is almost flat. The code is already more than 1000x faster when running a createinitialrevisions with 50000 objects in PostgreSQL.
Only constraint, it is Django 1.11+ only, but so is already at least the test suite, isn't it?
=> Update safe_subquery method to use exists as it is much much faster

reversion/models.py
This is an idea that may improve the performance of `get_deleted` for some of the users in #748.
The changes shift the subquery on the model on `get_deleted` to use the built-in `Exists` (only django versions 1.11 and up are listed as supported as of now, and `Exists` was added in this version). The subquery should work across supported backends, the test suite passes, and I've used locally in MySQL and Postgres successfully.
As far as performance goes, things get a bit tricky, and I've been able to look into query times only in Postgres at the moment. But, in Postgres, I've experienced performance changes similar similar to the following when running `get_deleted` on the entire `Version` queryset:
* For smaller models (in my testing, models with 10,000 or fewer instances), the original …
=> Use exists subquery to find deleted model instance pks

reversion/admin.py, reversion/models.py, reversion/revisions.py
The former is deprecated in Django 3.0 and has been an alias for force_str
since Django 2.0:
https://docs.djangoproject.com/en/3.0/releases/3.0/#django-utils-encoding-force-text-and-smart-text
Use of force_text raises deprecation warnings on Django 3.0.
=> Replace force_text with force_str

README.rst, setup.cfg, setup.py
- Enforce Python 3.6+
- Make wheels non-universal (Python 2 support is missing for universal)
- Add a long description for https://pypi.org/project/django-reversion/
=> Adjust setup

reversion/revisions.py, tests/test_app/tests/test_api.py
Alternative implementation for #816 
Closes #818
=> Alternative: Properly support revisions in on_commit handlers

reversion/revisions.py, tests/test_app/tests/test_api.py
Before this commit, making a second revision after a first atomic
revision transaction has successfully committed does not work properly.
Now, making a new atomic revision inside an on_commit handler works as
expected.
Implementation-wise it looks like it was already supposed to work, but
the internal local stack bookkeeping pops the current frame off the
stack just too late when exiting the contexts. This tricked the
bookkeeping into skipping the second revision creation.
=> Properly support revisions in on_commit handlers

CHANGELOG.rst
When upgrading from old versions it's necessary to incrementally upgrade at version `3.0.1`, run migrations, and then proceed.
[See here for more info](https://github.com/etianen/django-reversion/issues/822#issuecomment-621361180)
=> Update Changelog to add upgrade note

reversion/admin.py, tests/test_app/urls.py, tests/test_project/urls.py
replaced url() with re_path() and path() functions
=> url() is deprecated in Django 3.1

.travis.yml, tests/test_app/tests/test_api.py, tests/test_app/tests/test_commands.py, tests/test_app/tests/test_models.py
- `databases` was introduced in Django 2.2, see https://docs.djangoproject.com/en/dev/releases/2.2/#tests
- `multi_db` was deprecated at the same time, see https://docs.djangoproject.com/en/dev/releases/2.2/#id2
=> Run tests against Django 3.1

.github/workflows/python-package.yml, reversion/admin.py
Hi (👋 ), thanks for everything you do to maintain this project. 
When testing against Django 4.0a1 I see the tests failing for this one change. Hopefully I have captured the way you setup the tests correctly. 🤞 
Thanks again!
=> Added support for Django 4.0

.github/workflows/python-package.yml, setup.py
[Django >4.0.x supports Python 3.10](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django) so would be good to test against it. All the tests passed locally (Django==4.0.0b1, Python 3.10.0) with postgres but didn't test mysql.
Thought it was better to make it not very DRY and explicitly _exclude_ the older Django versions then having a single _include_ for 3.10 and forgetting to add another include when 4.1.x is released.
=> Python 3.10: run automated tests for Django 4.0.x against Python 3.10

reversion/management/commands/createinitialrevisions.py
Rather than retrieving the list of PKs that needs revisions created for, and then pulling out the actual objects in separate queries using `in_bulk`, we drop it down to a single `count()` query (to get the total number) and an `iterator()` query. This improves the performance (and possibly memory usage) on postgres databases when server side cursors are enabled (which they are by default on postgres databases). For databases where server side cursors are not enabled, we revert to the original code as `iterator()` is memory intensive (at the database driver level, see Django documentation on `iterator()` for further details).
My local tests suggest that this provides a speed-up of a factor of 2. Would be good if someone else could verify to confirm that's not just an artefact of my set-up …
=> Improved performance of `createinitialrevisions` management command on postgres databases

.github/workflows/python-package.yml, README.rst, reversion/revisions.py, setup.py
Use contextvars instead of threading.local to support async views.
I tried to do the smallest changes that I could, but using contextvars that code can be simplified a lot.
=> Support asyncio views

reversion/admin.py
There's a bug with false-positive trigger of **Cannot use VersionAdmin with a database that does not support savepoints.** exception on the admin page of a versioned model. It can be reproduced with Django configuration with multiple databases:
```
DATABASES = {
'default': {},
'db1': {
'ENGINE': 'django.db.backends.postgresql',
...
},
'db2': {
'ENGINE': 'django.db.backends.postgresql',
...
}
}
```
Thus, `connection.features.uses_savepoints` is irrelevant and should be replaced with `connections[version.db].features.uses_savepoints`.
=> Fix admin detail view in multi-database environment

.github/workflows/python-package.yml, docs/conf.py, reversion/admin.py, reversion/management/commands/__init__.py, reversion/management/commands/createinitialrevisions.py, reversion/migrations/0001_squashed_0004_auto_20160611_1202.py, reversion/models.py, reversion/revisions.py, reversion/views.py, setup.py, tests/test_app/tests/base.py, tests/test_app/tests/test_admin.py, tests/test_app/tests/test_api.py, tests/test_app/tests/test_models.py, tests/test_app/views.py, tests/test_project/urls.py
Hi ! This PR introduces support of Django 4.1
Also removes support of deprecated Django versions (all of those below 3.2 LTS).
I've run both pyupgrade and django-upgrade and isolated these changes in separate commits. Feel free to squash them.
=> Add support of Django 4.1

reversion/revisions.py, tests/test_app/migrations/0001_initial.py, tests/test_app/models.py, tests/test_app/tests/test_models.py
Good evening,
Thank you for creating awesome library!
At the moment I found one corner case that I can't workaround without monkey patching reversion library.
Let say we enabled reversion middleware for every view within the project.
Let say in a signal receiver a database exception was catched.
I'm aware that programmers should [avoid catching exceptions inside atomic block](https://docs.djangoproject.com/en/4.1/topics/db/transactions/#controlling-transactions-explicitly).
Unfortunately, such code could be placed in a poorly-written third-party package that we are forced to use.
Without reversion enabled such code block would rollback transaction and delegate execution to the view management code.
With reversion enabled the same code would fail with transaction management error.
You …
=> Do not try to create revision if current transaction is under rollback.

reversion/models.py
_Fixes #750_
This will be welcomed by users explicitly declaring `fields` with [`@reversion.register`](https://github.com/etianen/django-reversion/blob/v5.0.2/reversion/revisions.py#L363) ([docs](https://django-reversion.readthedocs.io/en/release-1.10.2/api.html#saving-a-subset-of-fields)).
Add a [`logging`](https://docs.python.org/3/library/logging.html) message for [`IntegrityError`](https://docs.djangoproject.com/en/4.1/ref/exceptions/#django.db.IntegrityError)
[`logging.traceback()`](https://docs.python.org/3/library/logging.html#logging.exception) offered the perfect level of detail to see which field(s) it's stuck on.
<details>
<summary>Example logging message</summary>
```
Traceback (most recent call last):
File "~/projects/django-site/.venv/lib/python3.10/site-packages/django/db/ba …
```
=> `_safe_revert`: Add a `logging` statement for `IntegrityError`

README.rst
The minimum version of Django was updated in https://github.com/etianen/django-reversion/pull/917 but the readme still showed 2.0 as supported.
=> Update Django version required in README to 3.2

CHANGELOG.rst
Sorry the previous pull request added the log to the wrong version, also adds the author name according to https://github.com/etianen/django-reversion/pull/801
=> Move dropping Python 2.7 changelog to correct version

reversion/models.py
This subquery is not nessesary and only cause huge load and slow recovery page load time.
=> fix: speed up get deleted. remove unnecessary subquery

reversion/models.py
Reverts etianen/django-reversion#951
=> Revert "fix: speed up get deleted. remove unnecessary subquery"

reversion/admin.py
While running a project with django-reversion and Sentry we found out there's one template that makes a query to the DB on every iteration. This PR fixes that
https://docs.sentry.io/product/issues/issue-details/performance-issues/n-one-queries/
https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet.select_related
=> perf: Fixes N+1 queries while rendering the recover_list.html template

reversion/revisions.py
This fixes #924.
I see the test suite already runs with both postgres and mysql, so in that regard both of these branches should already get covered across the existing test suite. Let me know if it makes sense to add more tests around this switching specifically!
=> Re-introduce bulk_create on supported databases
