etianen/django-reversion

- src/reversion/admin.py
> Update admin.py to avoid RemovedInDjango19Warning

- README.rst
Recent changes to the test-running procedure were not reflected in the README.
I assumed the process used currently for TravisCI is the correct one, but there may be a better way?
> Fix instructions for running tests in README.rst

- docs/commands.rst
I was going to implement functionality to delete old revisions and suddenly discovered its already there. This is my attempt to document the 'deleterevisions' command slightly.
> Document deleterevisions command

- src/reversion/management/commands/createinitialrevisions.py
> Simplify imports in createinitialrevisions

- src/reversion/models.py
> Added missing explicit on_delete arguments to ForeignKey

- src/reversion/revisions.py
small chunk of a bigger refactoring I'm trying to reach.
> One liner refactoring

- src/reversion/management/commands/deleterevisions.py
closes #516 
When Django management commands have a means of skipping confirmation
checks, usually the flag is '--no-input'. The 'deleterevisons' command
uses '--no-confirmation'. Since it functions exactly as you would expect
'--no-input', it makes sense to follow convention. The existing
'--no-confirmation' flag is left deprecated, but there is no schedule
for removal, nor is there a need to remove it any time soon.
Tested by running the test project. I didn't get a deprecation warning to pop up, but I can't tell if that's just me or if I did something wrong.
```
$ cd src/tests
$ ./manage.py migrate
$ python -Walways manage.py deleterevisions
All revisions will be deleted for all models.
Are you sure you want to delete theses revisions? [y|N] y
Deleting revisions...
Done
$ python …
```
> Add --no-input so management commands look similar to other Django commands

- reversion/migrations/0003_auto_20160601_1600.py
In relation to #559.
I believe using the `.using()` method on the object manager is best-practice for Django migrations.  I would like to see if @xuchen81 can verify that this resolves his issues before merging this.
> Use db-aware queries in migration

- docs/api.rst
I noticed that this is included twice in a row, thanks for the project!
> Remove duplicated API doc

- reversion/admin.py
- tests/test_app/tests/base.py
- tests/test_app/tests/test_admin.py
> Fixed revision message format on Django 1.10

- reversion/migrations/0003_auto_20160601_1600.py
Migration 0003 could be really slow on DBs with a lot of revisions/versions. This PR speed it up by:
* using content type id instead of app label and model name, thus eliminating join in update
* since multi-db is used by relatively small amount of Django apps, there is special path for single db (default) apps to not filter rows, but update all of them
> Speedup 0003 migration

- docs/commands.rst
More details on deleting revisions. Most typical usage.
3 commands I've found most useful with details what will happen.
Code is nice and allows stacking of --keep and --days, but nothing about that in docs.
> Details on deleting revisions

- docs/django-versions.rst
> More precice supported version matrix

- CHANGELOG.rst
Fix just fix wrong data 23/01/2017 --> 23/01/2018
> Fix typo in last changelog date

- README.rst
Add Pypi badges and put in the head. 
If you want to see how is rendered after the change follows the link below:
https://github.com/rhenter/django-reversion
> Refactor Readme to use Pypi badges

- reversion/models.py
In many cases `django-admin` is not used and it is an overhead for the project. Using `django-reversion` forces the developer to include `django.contrib.admin` in the `INSTALLED_APPS` even if it is not used. This is because it imports the `LogEntry` model from `django-admin` in one of the files.
This PR closes issue #744 by making the dependency of the `LogEntry` model from `django.contrib.admin` application optional. Moreover, unused imports have been removed and sorted.
> Remove django.contrib.admin dependency from django-reversion

- reversion/management/commands/__init__.py
> Check django.contrib.admin in INSTALLED_APPS when loading models

- reversion/models.py
Updates models.py to use gettext_lazy instead of ugettext_lazy
> Replaces ugettext_lazy by gettext_lazy

- reversion/models.py
Optimization is based on
1) switching casting to an appropriate type for Version.object_id instead of the primary key
2) for Postgres on using DISTINCT ON with conditional expressions
> Optimize deleted objects query

- docs/common-problems.rst
See also: https://github.com/etianen/django-reversion/issues/859
> docs: Add "incompatible version data" in "common problems"

- CHANGELOG.rst
- reversion/admin.py
- reversion/views.py
- tests/test_app/views.py
> Not rolling back revision on 400 status code

- reversion/models.py
Fixes the RemovedInDjango40Warning warning
> Replace ugettext by gettext

- reversion/models.py
9295e00 was missed, fix for #921's new message
> fix(_safe_revert): Missing f-string

- tests/test_project/settings.py
> Set default auto field in tests.

- reversion/admin.py
> Handling case of missing object in admin revert
